# -*- coding: utf-8 -*-
#
# This file is auto generated.

from __future__ import unicode_literals
from collections import namedtuple

Region = namedtuple('Region', 'alpha3 alpha2 numeric name uppername fullname')

REGIONS = [
    Region('ABW', 'AW', '533',
           'Aruba',
           'ARUBA',
           'Aruba'),
    Region('AFG', 'AF', '004',
           'Afghanistan',
           'AFGHANISTAN',
           'Islamic Republic of Afghanistan'),
    Region('AGO', 'AO', '024',
           'Angola',
           'ANGOLA',
           'Republic of Angola'),
    Region('AIA', 'AI', '660',
           'Anguilla',
           'ANGUILLA',
           'Anguilla'),
    Region('ALB', 'AL', '008',
           'Albania',
           'ALBANIA',
           'Republic of Albania'),
    Region('AND', 'AD', '020',
           'Andorra',
           'ANDORRA',
           'Principality of Andorra'),
    Region('ARE', 'AE', '784',
           'United Arab Emirates',
           'UNITED ARAB EMIRATES',
           'United Arab Emirates'),
    Region('ARG', 'AR', '032',
           'Argentina',
           'ARGENTINA',
           'Argentine Republic'),
    Region('ARM', 'AM', '051',
           'Armenia',
           'ARMENIA',
           'Republic of Armenia'),
    Region('ASM', 'AS', '016',
           'American Samoa',
           'AMERICAN SAMOA',
           'Territory of American Samoa'),
    Region('ATA', 'AQ', '010',
           'Antarctica',
           'ANTARCTICA',
           'Antarctica'),
    Region('ATF', 'TF', '260',
           'French Southern and Antarctic Lands',
           'FRENCH SOUTHERN AND ANTARCTIC LANDS',
           'French Southern and Antarctic Lands'),
    Region('ATG', 'AG', '028',
           'Antigua and Barbuda',
           'ANTIGUA AND BARBUDA',
           'Antigua and Barbuda'),
    Region('AUS', 'AU', '036',
           'Australia',
           'AUSTRALIA',
           'Commonwealth of Australia'),
    Region('AUT', 'AT', '040',
           'Austria',
           'AUSTRIA',
           'Republic of Austria'),
    Region('AZE', 'AZ', '031',
           'Azerbaijan',
           'AZERBAIJAN',
           'Republic of Azerbaijan'),
    Region('BDI', 'BI', '108',
           'Burundi',
           'BURUNDI',
           'Republic of Burundi'),
    Region('BEL', 'BE', '056',
           'Belgium',
           'BELGIUM',
           'Kingdom of Belgium'),
    Region('BEN', 'BJ', '204',
           'Benin',
           'BENIN',
           'Republic of Benin'),
    Region('BES', 'BQ', '535',
           'Bonaire, Sint Eustatius, and Saba',
           'BONAIRE, SINT EUSTATIUS, AND SABA',
           'Bonaire, Sint Eustatius, and Saba'),
    Region('BFA', 'BF', '854',
           'Burkina Faso',
           'BURKINA FASO',
           'Burkina Faso'),
    Region('BGD', 'BD', '050',
           'Bangladesh',
           'BANGLADESH',
           'People’s Republic of Bangladesh'),
    Region('BGR', 'BG', '100',
           'Bulgaria',
           'BULGARIA',
           'Republic of Bulgaria'),
    Region('BHR', 'BH', '048',
           'Bahrain',
           'BAHRAIN',
           'Kingdom of Bahrain'),
    Region('BHS', 'BS', '044',
           'Bahamas, The',
           'BAHAMAS, THE',
           'Commonwealth of The Bahamas'),
    Region('BIH', 'BA', '070',
           'Bosnia and Herzegovina',
           'BOSNIA AND HERZEGOVINA',
           'Bosnia and Herzegovina'),
    Region('BLM', 'BL', '652',
           'Saint Barthelemy',
           'SAINT BARTHELEMY',
           'Saint Barthelemy'),
    Region('BLR', 'BY', '112',
           'Belarus',
           'BELARUS',
           'Republic of Belarus'),
    Region('BLZ', 'BZ', '084',
           'Belize',
           'BELIZE',
           'Belize'),
    Region('BMU', 'BM', '060',
           'Bermuda',
           'BERMUDA',
           'Bermuda'),
    Region('BOL', 'BO', '068',
           'Bolivia',
           'BOLIVIA',
           'Plurinational State of Bolivia'),
    Region('BRA', 'BR', '076',
           'Brazil',
           'BRAZIL',
           'Federative Republic of Brazil'),
    Region('BRB', 'BB', '052',
           'Barbados',
           'BARBADOS',
           'Barbados'),
    Region('BRN', 'BN', '096',
           'Brunei',
           'BRUNEI',
           'Brunei Darussalam'),
    Region('BTN', 'BT', '064',
           'Bhutan',
           'BHUTAN',
           'Kingdom of Bhutan'),
    Region('BVT', 'BV', '074',
           'Bouvet Island',
           'BOUVET ISLAND',
           'Bouvet Island'),
    Region('BWA', 'BW', '072',
           'Botswana',
           'BOTSWANA',
           'Republic of Botswana'),
    Region('CAF', 'CF', '140',
           'Central African Republic',
           'CENTRAL AFRICAN REPUBLIC',
           'Central African Republic'),
    Region('CAN', 'CA', '124',
           'Canada',
           'CANADA',
           'Canada'),
    Region('CCK', 'CC', '166',
           'Cocos (Keeling) Islands',
           'COCOS (KEELING) ISLANDS',
           'Territory of Cocos (Keeling) Islands'),
    Region('CHE', 'CH', '756',
           'Switzerland',
           'SWITZERLAND',
           'Swiss Confederation'),
    Region('CHL', 'CL', '152',
           'Chile',
           'CHILE',
           'Republic of Chile'),
    Region('CHN', 'CN', '156',
           'China',
           'CHINA',
           'People’s Republic of China'),
    Region('CIV', 'CI', '384',
           'Côte d’Ivoire',
           'CÔTE D’IVOIRE',
           'Republic of Côte d’Ivoire'),
    Region('CMR', 'CM', '120',
           'Cameroon',
           'CAMEROON',
           'Republic of Cameroon'),
    Region('COD', 'CD', '180',
           'Congo (Kinshasa)',
           'CONGO (KINSHASA)',
           'Democratic Republic of the Congo'),
    Region('COG', 'CG', '178',
           'Congo (Brazzaville)',
           'CONGO (BRAZZAVILLE)',
           'Republic of the Congo'),
    Region('COK', 'CK', '184',
           'Cook Islands',
           'COOK ISLANDS',
           'Cook Islands'),
    Region('COL', 'CO', '170',
           'Colombia',
           'COLOMBIA',
           'Republic of Colombia'),
    Region('COM', 'KM', '174',
           'Comoros',
           'COMOROS',
           'Union of the Comoros'),
    Region('CPT', 'CP', '905',
           'Clipperton Island',
           'CLIPPERTON ISLAND',
           'Clipperton Island'),
    Region('CPV', 'CV', '132',
           'Cabo Verde',
           'CABO VERDE',
           'Republic of Cabo Verde'),
    Region('CRI', 'CR', '188',
           'Costa Rica',
           'COSTA RICA',
           'Republic of Costa Rica'),
    Region('CUB', 'CU', '192',
           'Cuba',
           'CUBA',
           'Republic of Cuba'),
    Region('CUW', 'CW', '531',
           'Curaçao',
           'CURAÇAO',
           'Curaçao'),
    Region('CXR', 'CX', '162',
           'Christmas Island',
           'CHRISTMAS ISLAND',
           'Territory of Christmas Island'),
    Region('CYM', 'KY', '136',
           'Cayman Islands',
           'CAYMAN ISLANDS',
           'Cayman Islands'),
    Region('CYP', 'CY', '196',
           'Cyprus',
           'CYPRUS',
           'Republic of Cyprus'),
    Region('CZE', 'CZ', '203',
           'Czech Republic',
           'CZECH REPUBLIC',
           'Czech Republic'),
    Region('DEU', 'DE', '276',
           'Germany',
           'GERMANY',
           'Federal Republic of Germany'),
    Region('DGA', 'DG', '908',
           'Diego Garcia',
           'DIEGO GARCIA',
           'Diego Garcia'),
    Region('DJI', 'DJ', '262',
           'Djibouti',
           'DJIBOUTI',
           'Republic of Djibouti'),
    Region('DMA', 'DM', '212',
           'Dominica',
           'DOMINICA',
           'Commonwealth of Dominica'),
    Region('DNK', 'DK', '208',
           'Denmark',
           'DENMARK',
           'Kingdom of Denmark'),
    Region('DOM', 'DO', '214',
           'Dominican Republic',
           'DOMINICAN REPUBLIC',
           'Dominican Republic'),
    Region('DZA', 'DZ', '012',
           'Algeria',
           'ALGERIA',
           'People’s Democratic Republic of Algeria'),
    Region('ECU', 'EC', '218',
           'Ecuador',
           'ECUADOR',
           'Republic of Ecuador'),
    Region('EGY', 'EG', '818',
           'Egypt',
           'EGYPT',
           'Arab Republic of Egypt'),
    Region('ERI', 'ER', '232',
           'Eritrea',
           'ERITREA',
           'State of Eritrea'),
    Region('ESH', 'EH', '732',
           'Western Sahara',
           'WESTERN SAHARA',
           'Western Sahara'),
    Region('ESP', 'ES', '724',
           'Spain',
           'SPAIN',
           'Kingdom of Spain'),
    Region('EST', 'EE', '233',
           'Estonia',
           'ESTONIA',
           'Republic of Estonia'),
    Region('ETH', 'ET', '231',
           'Ethiopia',
           'ETHIOPIA',
           'Federal Democratic Republic of Ethiopia'),
    Region('FIN', 'FI', '246',
           'Finland',
           'FINLAND',
           'Republic of Finland'),
    Region('FJI', 'FJ', '242',
           'Fiji',
           'FIJI',
           'Republic of Fiji'),
    Region('FLK', 'FK', '238',
           'Falkland Islands (Islas Malvinas)',
           'FALKLAND ISLANDS (ISLAS MALVINAS)',
           'Falkland Islands (Islas Malvinas)'),
    Region('FRA', 'FR', '250',
           'France',
           'FRANCE',
           'French Republic'),
    Region('FRO', 'FO', '234',
           'Faroe Islands',
           'FAROE ISLANDS',
           'Faroe Islands'),
    Region('FSM', 'FM', '583',
           'Micronesia, Federated States of',
           'MICRONESIA, FEDERATED STATES OF',
           'Federated States of Micronesia'),
    Region('GAB', 'GA', '266',
           'Gabon',
           'GABON',
           'Gabonese Republic'),
    Region('GBR', 'GB', '826',
           'United Kingdom',
           'UNITED KINGDOM',
           'United Kingdom of Great Britain and Northern Ireland'),
    Region('GEO', 'GE', '268',
           'Georgia',
           'GEORGIA',
           'Georgia'),
    Region('GGY', 'GG', '831',
           'Guernsey',
           'GUERNSEY',
           'Bailiwick of Guernsey'),
    Region('GHA', 'GH', '288',
           'Ghana',
           'GHANA',
           'Republic of Ghana'),
    Region('GIB', 'GI', '292',
           'Gibraltar',
           'GIBRALTAR',
           'Gibraltar'),
    Region('GIN', 'GN', '324',
           'Guinea',
           'GUINEA',
           'Republic of Guinea'),
    Region('GLP', 'GP', '312',
           'Guadeloupe',
           'GUADELOUPE',
           'Department of Guadeloupe'),
    Region('GMB', 'GM', '270',
           'Gambia, The',
           'GAMBIA, THE',
           'Republic of The Gambia'),
    Region('GNB', 'GW', '624',
           'Guinea-Bissau',
           'GUINEA-BISSAU',
           'Republic of Guinea-Bissau'),
    Region('GNQ', 'GQ', '226',
           'Equatorial Guinea',
           'EQUATORIAL GUINEA',
           'Republic of Equatorial Guinea'),
    Region('GRC', 'GR', '300',
           'Greece',
           'GREECE',
           'Hellenic Republic'),
    Region('GRD', 'GD', '308',
           'Grenada',
           'GRENADA',
           'Grenada'),
    Region('GRL', 'GL', '304',
           'Greenland',
           'GREENLAND',
           'Greenland'),
    Region('GTM', 'GT', '320',
           'Guatemala',
           'GUATEMALA',
           'Republic of Guatemala'),
    Region('GUF', 'GF', '254',
           'French Guiana',
           'FRENCH GUIANA',
           'Department of Guiana'),
    Region('GUM', 'GU', '316',
           'Guam',
           'GUAM',
           'Territory of Guam'),
    Region('GUY', 'GY', '328',
           'Guyana',
           'GUYANA',
           'Co-operative Republic of Guyana'),
    Region('HKG', 'HK', '344',
           'Hong Kong',
           'HONG KONG',
           'Hong Kong Special Administrative Region'),
    Region('HMD', 'HM', '334',
           'Heard Island and McDonald Islands',
           'HEARD ISLAND AND MCDONALD ISLANDS',
           'Territory of Heard Island and McDonald Islands'),
    Region('HND', 'HN', '340',
           'Honduras',
           'HONDURAS',
           'Republic of Honduras'),
    Region('HRV', 'HR', '191',
           'Croatia',
           'CROATIA',
           'Republic of Croatia'),
    Region('HTI', 'HT', '332',
           'Haiti',
           'HAITI',
           'Republic of Haiti'),
    Region('HUN', 'HU', '348',
           'Hungary',
           'HUNGARY',
           'Hungary'),
    Region('IDN', 'ID', '360',
           'Indonesia',
           'INDONESIA',
           'Republic of Indonesia'),
    Region('IMN', 'IM', '833',
           'Isle of Man',
           'ISLE OF MAN',
           'Isle of Man'),
    Region('IND', 'IN', '356',
           'India',
           'INDIA',
           'Republic of India'),
    Region('IOT', 'IO', '086',
           'British Indian Ocean Territory',
           'BRITISH INDIAN OCEAN TERRITORY',
           'British Indian Ocean Territory'),
    Region('IRL', 'IE', '372',
           'Ireland',
           'IRELAND',
           'Ireland'),
    Region('IRN', 'IR', '364',
           'Iran',
           'IRAN',
           'Islamic Republic of Iran'),
    Region('IRQ', 'IQ', '368',
           'Iraq',
           'IRAQ',
           'Republic of Iraq'),
    Region('ISL', 'IS', '352',
           'Iceland',
           'ICELAND',
           'Republic of Iceland'),
    Region('ISR', 'IL', '376',
           'Israel',
           'ISRAEL',
           'State of Israel'),
    Region('ITA', 'IT', '380',
           'Italy',
           'ITALY',
           'Italian Republic'),
    Region('JAM', 'JM', '388',
           'Jamaica',
           'JAMAICA',
           'Jamaica'),
    Region('JEY', 'JE', '832',
           'Jersey',
           'JERSEY',
           'Bailiwick of Jersey'),
    Region('JOR', 'JO', '400',
           'Jordan',
           'JORDAN',
           'Hashemite Kingdom of Jordan'),
    Region('JPN', 'JP', '392',
           'Japan',
           'JAPAN',
           'Japan'),
    Region('KAZ', 'KZ', '398',
           'Kazakhstan',
           'KAZAKHSTAN',
           'Republic of Kazakhstan'),
    Region('KEN', 'KE', '404',
           'Kenya',
           'KENYA',
           'Republic of Kenya'),
    Region('KGZ', 'KG', '417',
           'Kyrgyzstan',
           'KYRGYZSTAN',
           'Kyrgyz Republic'),
    Region('KHM', 'KH', '116',
           'Cambodia',
           'CAMBODIA',
           'Kingdom of Cambodia'),
    Region('KIR', 'KI', '296',
           'Kiribati',
           'KIRIBATI',
           'Republic of Kiribati'),
    Region('KNA', 'KN', '659',
           'Saint Kitts and Nevis',
           'SAINT KITTS AND NEVIS',
           'Federation of Saint Kitts and Nevis'),
    Region('KOR', 'KR', '410',
           'Korea, South',
           'KOREA, SOUTH',
           'Republic of Korea'),
    Region('KWT', 'KW', '414',
           'Kuwait',
           'KUWAIT',
           'State of Kuwait'),
    Region('LAO', 'LA', '418',
           'Laos',
           'LAOS',
           'Lao People’s Democratic Republic'),
    Region('LBN', 'LB', '422',
           'Lebanon',
           'LEBANON',
           'Lebanese Republic'),
    Region('LBR', 'LR', '430',
           'Liberia',
           'LIBERIA',
           'Republic of Liberia'),
    Region('LBY', 'LY', '434',
           'Libya',
           'LIBYA',
           'Libya'),
    Region('LCA', 'LC', '662',
           'Saint Lucia',
           'SAINT LUCIA',
           'Saint Lucia'),
    Region('LIE', 'LI', '438',
           'Liechtenstein',
           'LIECHTENSTEIN',
           'Principality of Liechtenstein'),
    Region('LKA', 'LK', '144',
           'Sri Lanka',
           'SRI LANKA',
           'Democratic Socialist Republic of Sri Lanka'),
    Region('LSO', 'LS', '426',
           'Lesotho',
           'LESOTHO',
           'Kingdom of Lesotho'),
    Region('LTU', 'LT', '440',
           'Lithuania',
           'LITHUANIA',
           'Republic of Lithuania'),
    Region('LUX', 'LU', '442',
           'Luxembourg',
           'LUXEMBOURG',
           'Grand Duchy of Luxembourg'),
    Region('LVA', 'LV', '428',
           'Latvia',
           'LATVIA',
           'Republic of Latvia'),
    Region('MAC', 'MO', '446',
           'Macau',
           'MACAU',
           'Macau Special Administrative Region'),
    Region('MAF', 'MF', '663',
           'Saint Martin',
           'SAINT MARTIN',
           'Saint Martin'),
    Region('MAR', 'MA', '504',
           'Morocco',
           'MOROCCO',
           'Kingdom of Morocco'),
    Region('MCO', 'MC', '492',
           'Monaco',
           'MONACO',
           'Principality of Monaco'),
    Region('MDA', 'MD', '498',
           'Moldova',
           'MOLDOVA',
           'Republic of Moldova'),
    Region('MDG', 'MG', '450',
           'Madagascar',
           'MADAGASCAR',
           'Republic of Madagascar'),
    Region('MDV', 'MV', '462',
           'Maldives',
           'MALDIVES',
           'Republic of Maldives'),
    Region('MEX', 'MX', '484',
           'Mexico',
           'MEXICO',
           'United Mexican States'),
    Region('MHL', 'MH', '584',
           'Marshall Islands',
           'MARSHALL ISLANDS',
           'Republic of the Marshall Islands'),
    Region('MKD', 'MK', '807',
           'Macedonia',
           'MACEDONIA',
           'Republic of Macedonia'),
    Region('MLI', 'ML', '466',
           'Mali',
           'MALI',
           'Republic of Mali'),
    Region('MLT', 'MT', '470',
           'Malta',
           'MALTA',
           'Republic of Malta'),
    Region('MMR', 'MM', '104',
           'Burma',
           'BURMA',
           'Union of Burma'),
    Region('MNE', 'ME', '499',
           'Montenegro',
           'MONTENEGRO',
           'Montenegro'),
    Region('MNG', 'MN', '496',
           'Mongolia',
           'MONGOLIA',
           'Mongolia'),
    Region('MNP', 'MP', '580',
           'Northern Mariana Islands',
           'NORTHERN MARIANA ISLANDS',
           'Commonwealth of the Northern Mariana Islands'),
    Region('MOZ', 'MZ', '508',
           'Mozambique',
           'MOZAMBIQUE',
           'Republic of Mozambique'),
    Region('MRT', 'MR', '478',
           'Mauritania',
           'MAURITANIA',
           'Islamic Republic of Mauritania'),
    Region('MSR', 'MS', '500',
           'Montserrat',
           'MONTSERRAT',
           'Montserrat'),
    Region('MTQ', 'MQ', '474',
           'Martinique',
           'MARTINIQUE',
           'Department of Martinique'),
    Region('MUS', 'MU', '480',
           'Mauritius',
           'MAURITIUS',
           'Republic of Mauritius'),
    Region('MWI', 'MW', '454',
           'Malawi',
           'MALAWI',
           'Republic of Malawi'),
    Region('MYS', 'MY', '458',
           'Malaysia',
           'MALAYSIA',
           'Malaysia'),
    Region('MYT', 'YT', '175',
           'Mayotte',
           'MAYOTTE',
           'Department of Mayotte'),
    Region('NAM', 'NA', '516',
           'Namibia',
           'NAMIBIA',
           'Republic of Namibia'),
    Region('NCL', 'NC', '540',
           'New Caledonia',
           'NEW CALEDONIA',
           'New Caledonia'),
    Region('NER', 'NE', '562',
           'Niger',
           'NIGER',
           'Republic of Niger'),
    Region('NFK', 'NF', '574',
           'Norfolk Island',
           'NORFOLK ISLAND',
           'Territory of Norfolk Island'),
    Region('NGA', 'NG', '566',
           'Nigeria',
           'NIGERIA',
           'Federal Republic of Nigeria'),
    Region('NIC', 'NI', '558',
           'Nicaragua',
           'NICARAGUA',
           'Republic of Nicaragua'),
    Region('NIU', 'NU', '570',
           'Niue',
           'NIUE',
           'Niue'),
    Region('NLD', 'NL', '528',
           'Netherlands',
           'NETHERLANDS',
           'Kingdom of the Netherlands'),
    Region('NOR', 'NO', '578',
           'Norway',
           'NORWAY',
           'Kingdom of Norway'),
    Region('NPL', 'NP', '524',
           'Nepal',
           'NEPAL',
           'Federal Democratic Republic of Nepal'),
    Region('NRU', 'NR', '520',
           'Nauru',
           'NAURU',
           'Republic of Nauru'),
    Region('NZL', 'NZ', '554',
           'New Zealand',
           'NEW ZEALAND',
           'New Zealand'),
    Region('OMN', 'OM', '512',
           'Oman',
           'OMAN',
           'Sultanate of Oman'),
    Region('PAK', 'PK', '586',
           'Pakistan',
           'PAKISTAN',
           'Islamic Republic of Pakistan'),
    Region('PAN', 'PA', '591',
           'Panama',
           'PANAMA',
           'Republic of Panama'),
    Region('PCN', 'PN', '612',
           'Pitcairn Islands',
           'PITCAIRN ISLANDS',
           'Pitcairn, Henderson, Ducie, and Oeno Islands'),
    Region('PER', 'PE', '604',
           'Peru',
           'PERU',
           'Republic of Peru'),
    Region('PHL', 'PH', '608',
           'Philippines',
           'PHILIPPINES',
           'Republic of the Philippines'),
    Region('PLW', 'PW', '585',
           'Palau',
           'PALAU',
           'Republic of Palau'),
    Region('PNG', 'PG', '598',
           'Papua New Guinea',
           'PAPUA NEW GUINEA',
           'Independent State of Papua New Guinea'),
    Region('POL', 'PL', '616',
           'Poland',
           'POLAND',
           'Republic of Poland'),
    Region('PRI', 'PR', '630',
           'Puerto Rico',
           'PUERTO RICO',
           'Commonwealth of Puerto Rico'),
    Region('PRK', 'KP', '408',
           'Korea, North',
           'KOREA, NORTH',
           'Democratic People’s Republic of Korea'),
    Region('PRT', 'PT', '620',
           'Portugal',
           'PORTUGAL',
           'Portuguese Republic'),
    Region('PRY', 'PY', '600',
           'Paraguay',
           'PARAGUAY',
           'Republic of Paraguay'),
    Region('PYF', 'PF', '258',
           'French Polynesia',
           'FRENCH POLYNESIA',
           'French Polynesia'),
    Region('QAT', 'QA', '634',
           'Qatar',
           'QATAR',
           'State of Qatar'),
    Region('REU', 'RE', '638',
           'Reunion',
           'REUNION',
           'Department of Reunion'),
    Region('ROU', 'RO', '642',
           'Romania',
           'ROMANIA',
           'Romania'),
    Region('RUS', 'RU', '643',
           'Russia',
           'RUSSIA',
           'Russian Federation'),
    Region('RWA', 'RW', '646',
           'Rwanda',
           'RWANDA',
           'Republic of Rwanda'),
    Region('SAU', 'SA', '682',
           'Saudi Arabia',
           'SAUDI ARABIA',
           'Kingdom of Saudi Arabia'),
    Region('SDN', 'SD', '729',
           'Sudan',
           'SUDAN',
           'Republic of the Sudan'),
    Region('SEN', 'SN', '686',
           'Senegal',
           'SENEGAL',
           'Republic of Senegal'),
    Region('SGP', 'SG', '702',
           'Singapore',
           'SINGAPORE',
           'Republic of Singapore'),
    Region('SGS', 'GS', '239',
           'South Georgia and South Sandwich Islands',
           'SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS',
           'South Georgia and the South Sandwich Islands'),
    Region('SHN', 'SH', '654',
           'Saint Helena, Ascension, and Tristan da Cunha',
           'SAINT HELENA, ASCENSION, AND TRISTAN DA CUNHA',
           'Saint Helena, Ascension, and Tristan da Cunha'),
    Region('SLB', 'SB', '090',
           'Solomon Islands',
           'SOLOMON ISLANDS',
           'Solomon Islands'),
    Region('SLE', 'SL', '694',
           'Sierra Leone',
           'SIERRA LEONE',
           'Republic of Sierra Leone'),
    Region('SLV', 'SV', '222',
           'El Salvador',
           'EL SALVADOR',
           'Republic of El Salvador'),
    Region('SMR', 'SM', '674',
           'San Marino',
           'SAN MARINO',
           'Republic of San Marino'),
    Region('SOM', 'SO', '706',
           'Somalia',
           'SOMALIA',
           'Federal Republic of Somalia'),
    Region('SPM', 'PM', '666',
           'Saint Pierre and Miquelon',
           'SAINT PIERRE AND MIQUELON',
           'Territorial Collectivity of Saint Pierre and Miquelon'),
    Region('SRB', 'RS', '688',
           'Serbia',
           'SERBIA',
           'Republic of Serbia'),
    Region('SSD', 'SS', '728',
           'South Sudan',
           'SOUTH SUDAN',
           'Republic of South Sudan'),
    Region('STP', 'ST', '678',
           'Sao Tome and Principe',
           'SAO TOME AND PRINCIPE',
           'Democratic Republic of Sao Tome and Principe'),
    Region('SUR', 'SR', '740',
           'Suriname',
           'SURINAME',
           'Republic of Suriname'),
    Region('SVK', 'SK', '703',
           'Slovakia',
           'SLOVAKIA',
           'Slovak Republic'),
    Region('SVN', 'SI', '705',
           'Slovenia',
           'SLOVENIA',
           'Republic of Slovenia'),
    Region('SWE', 'SE', '752',
           'Sweden',
           'SWEDEN',
           'Kingdom of Sweden'),
    Region('SWZ', 'SZ', '748',
           'Swaziland',
           'SWAZILAND',
           'Kingdom of Swaziland'),
    Region('SXM', 'SX', '534',
           'Sint Maarten',
           'SINT MAARTEN',
           'Sint Maarten'),
    Region('SYC', 'SC', '690',
           'Seychelles',
           'SEYCHELLES',
           'Republic of Seychelles'),
    Region('SYR', 'SY', '760',
           'Syria',
           'SYRIA',
           'Syrian Arab Republic'),
    Region('TCA', 'TC', '796',
           'Turks and Caicos Islands',
           'TURKS AND CAICOS ISLANDS',
           'Turks and Caicos Islands'),
    Region('TCD', 'TD', '148',
           'Chad',
           'CHAD',
           'Republic of Chad'),
    Region('TGO', 'TG', '768',
           'Togo',
           'TOGO',
           'Togolese Republic'),
    Region('THA', 'TH', '764',
           'Thailand',
           'THAILAND',
           'Kingdom of Thailand'),
    Region('TJK', 'TJ', '762',
           'Tajikistan',
           'TAJIKISTAN',
           'Republic of Tajikistan'),
    Region('TKL', 'TK', '772',
           'Tokelau',
           'TOKELAU',
           'Tokelau'),
    Region('TKM', 'TM', '795',
           'Turkmenistan',
           'TURKMENISTAN',
           'Turkmenistan'),
    Region('TLS', 'TL', '626',
           'Timor-Leste',
           'TIMOR-LESTE',
           'Democratic Republic of Timor-Leste'),
    Region('TON', 'TO', '776',
           'Tonga',
           'TONGA',
           'Kingdom of Tonga'),
    Region('TTO', 'TT', '780',
           'Trinidad and Tobago',
           'TRINIDAD AND TOBAGO',
           'Republic of Trinidad and Tobago'),
    Region('TUN', 'TN', '788',
           'Tunisia',
           'TUNISIA',
           'Republic of Tunisia'),
    Region('TUR', 'TR', '792',
           'Turkey',
           'TURKEY',
           'Republic of Turkey'),
    Region('TUV', 'TV', '798',
           'Tuvalu',
           'TUVALU',
           'Tuvalu'),
    Region('TWN', 'TW', '158',
           'Taiwan',
           'TAIWAN',
           'Taiwan'),
    Region('TZA', 'TZ', '834',
           'Tanzania',
           'TANZANIA',
           'United Republic of Tanzania'),
    Region('UGA', 'UG', '800',
           'Uganda',
           'UGANDA',
           'Republic of Uganda'),
    Region('UKR', 'UA', '804',
           'Ukraine',
           'UKRAINE',
           'Ukraine'),
    Region('URY', 'UY', '858',
           'Uruguay',
           'URUGUAY',
           'Oriental Republic of Uruguay'),
    Region('USA', 'US', '840',
           'United States',
           'UNITED STATES',
           'United States of America'),
    Region('UZB', 'UZ', '860',
           'Uzbekistan',
           'UZBEKISTAN',
           'Republic of Uzbekistan'),
    Region('VAT', 'VA', '336',
           'Vatican City',
           'VATICAN CITY',
           'State of the Vatican City'),
    Region('VCT', 'VC', '670',
           'Saint Vincent and the Grenadines',
           'SAINT VINCENT AND THE GRENADINES',
           'Saint Vincent and the Grenadines'),
    Region('VEN', 'VE', '862',
           'Venezuela',
           'VENEZUELA',
           'Bolivarian Republic of Venezuela'),
    Region('VGB', 'VG', '092',
           'Virgin Islands, British',
           'VIRGIN ISLANDS, BRITISH',
           'Virgin Islands, British'),
    Region('VIR', 'VI', '850',
           'Virgin Islands, U.S.',
           'VIRGIN ISLANDS, U.S.',
           'United States Virgin Islands'),
    Region('VNM', 'VN', '704',
           'Vietnam',
           'VIETNAM',
           'Socialist Republic of Vietnam'),
    Region('VUT', 'VU', '548',
           'Vanuatu',
           'VANUATU',
           'Republic of Vanuatu'),
    Region('WLF', 'WF', '876',
           'Wallis and Futuna',
           'WALLIS AND FUTUNA',
           'Wallis and Futuna'),
    Region('WSM', 'WS', '882',
           'Samoa',
           'SAMOA',
           'Independent State of Samoa'),
    Region('XAC', 'XA', '902',
           'Ashmore and Cartier Islands',
           'ASHMORE AND CARTIER ISLANDS',
           'Territory of Ashmore and Cartier Islands'),
    Region('XBI', 'QS', '904',
           'Bassas da India',
           'BASSAS DA INDIA',
           'Bassas da India'),
    Region('XBK', 'XB', '903',
           'Baker Island',
           'BAKER ISLAND',
           'Baker Island'),
    Region('XCS', 'XC', '906',
           'Coral Sea Islands',
           'CORAL SEA ISLANDS',
           'Coral Sea Islands Territory'),
    Region('XEU', 'XE', '915',
           'Europa Island',
           'EUROPA ISLAND',
           'Europa Island'),
    Region('XGL', 'QX', '917',
           'Glorioso Islands',
           'GLORIOSO ISLANDS',
           'Glorioso Islands'),
    Region('XGZ', 'XG', '916',
           'Gaza Strip',
           'GAZA STRIP',
           'Gaza Strip'),
    Region('XHO', 'XH', '919',
           'Howland Island',
           'HOWLAND ISLAND',
           'Howland Island'),
    Region('XJA', 'XU', '922',
           'Johnston Atoll',
           'JOHNSTON ATOLL',
           'Johnston Atoll'),
    Region('XJM', 'XJ', '920',
           'Jan Mayen',
           'JAN MAYEN',
           'Jan Mayen'),
    Region('XJN', 'QU', '923',
           'Juan de Nova Island',
           'JUAN DE NOVA ISLAND',
           'Juan de Nova Island'),
    Region('XJV', 'XQ', '921',
           'Jarvis Island',
           'JARVIS ISLAND',
           'Jarvis Island'),
    Region('XKR', 'XM', '924',
           'Kingman Reef',
           'KINGMAN REEF',
           'Kingman Reef'),
    Region('XKS', 'XK', '901',
           'Kosovo',
           'KOSOVO',
           'Republic of Kosovo'),
    Region('XMW', 'QM', '925',
           'Midway Islands',
           'MIDWAY ISLANDS',
           'Midway Islands'),
    Region('XNV', 'XV', '926',
           'Navassa Island',
           'NAVASSA ISLAND',
           'Navassa Island'),
    Region('XPL', 'XL', '927',
           'Palmyra Atoll',
           'PALMYRA ATOLL',
           'Palmyra Atoll'),
    Region('XPR', 'XP', '928',
           'Paracel Islands',
           'PARACEL ISLANDS',
           'Paracel Islands'),
    Region('XQZ', 'QZ', '900',
           'Akrotiri',
           'AKROTIRI',
           'Akrotiri'),
    Region('XSP', 'XS', '929',
           'Spratly Islands',
           'SPRATLY ISLANDS',
           'Spratly Islands'),
    Region('XSV', 'XR', '930',
           'Svalbard',
           'SVALBARD',
           'Svalbard'),
    Region('XTR', 'XT', '931',
           'Tromelin Island',
           'TROMELIN ISLAND',
           'Tromelin Island'),
    Region('XWB', 'XW', '934',
           'West Bank',
           'WEST BANK',
           'West Bank'),
    Region('XWK', 'QW', '933',
           'Wake Island',
           'WAKE ISLAND',
           'Wake Island'),
    Region('XXD', 'XD', '907',
           'Dhekelia',
           'DHEKELIA',
           'Dhekelia'),
    Region('YEM', 'YE', '887',
           'Yemen',
           'YEMEN',
           'Republic of Yemen'),
    Region('ZAF', 'ZA', '710',
           'South Africa',
           'SOUTH AFRICA',
           'Republic of South Africa'),
    Region('ZMB', 'ZM', '894',
           'Zambia',
           'ZAMBIA',
           'Republic of Zambia'),
    Region('ZWE', 'ZW', '716',
           'Zimbabwe',
           'ZIMBABWE',
           'Republic of Zimbabwe'),
]
